import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'zh' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    // Navigation
    'nav.dashboard': '儀表板',
    'nav.business': '商家管理',
    'nav.batchUpload': '批次上傳',
    'nav.events': '活動管理',
    'nav.analytics': '數據分析',
    'nav.tags': '標籤管理',
    'nav.categories': '分類管理',
    
    // Dashboard
    'dashboard.title': '儀表板',
    'dashboard.totalBusinesses': '總商家數',
    'dashboard.publishedBusinesses': '已上架商家',
    'dashboard.todayViews': '今日瀏覽量',
    'dashboard.runningEvents': '進行中活動',
    'dashboard.trafficTrend': '流量趨勢',
    'dashboard.topBusinesses': '熱門商家排行',
    'dashboard.recentActivity': '最近動態',
    'dashboard.pendingTasks': '待處理事項',
    'dashboard.pendingBusinesses': '待審核商家',
    'dashboard.activeEvents': '編輯中活動',
    'dashboard.compareLastWeek': '相較上週',
    'dashboard.viewDetails': '查看詳細',
    'dashboard.viewAll': '查看全部',
    'dashboard.editPhoto': '編輯照片',
    
    // Analytics
    'analytics.title': '數據分析',
    'analytics.totalViews': '總瀏覽量',
    'analytics.uniqueVisitors': '獨立訪問者',
    'analytics.totalClicks': '點擊數',
    'analytics.totalFavorites': '收藏數',
    'analytics.activeBusinesses': '活躍商家',
    'analytics.monthlyEvents': '本月活動',
    'analytics.thisMonthEvents': '本月活動',
    'analytics.trafficTrend': '流量趨勢',
    'analytics.businessCategoryDistribution': '商家分類分布',
    'analytics.visitors': '訪問者數',
    'analytics.pageViews': '頁面瀏覽量',
    'analytics.topBusinesses': '熱門商家排行',
    'analytics.deviceUsageStatistics': '設備使用統計',
    'analytics.sessions': '次',
    'analytics.eventStatistics': '活動統計',
    'analytics.publishedEvents': '已發布活動',
    'analytics.participatedTimes': '參與人次',
    'analytics.cancelledEvents': '取消活動',
    'analytics.last7Days': '近7天',
    'analytics.last30Days': '近30天',
    'analytics.last90Days': '近90天',
    'analytics.lastYear': '近1年',
    'analytics.exportReport': '導出報告',
    'analytics.viewMore': '查看更多',
    'analytics.businessViews': '商家瀏覽',
    'analytics.eventViews': '活動瀏覽',
    'analytics.mobile': '手機',
    'analytics.desktop': '桌面',
    'analytics.tablet': '平板',
    
    // Table columns
    'table.views': '瀏覽量',
    'table.clickThroughRate': '點擊率',
    'table.interactionRate': '互動率',
    'table.ctr': 'CTR',
    'table.browse': '瀏覽',
    'table.totalViews': '總瀏覽量',
    'table.avgClickThroughRate': '平均點擊率',
    'table.participatingEvents': '參與活動',
    'table.noEvents': '無活動',
    'table.events': '個活動',
    
    // Categories
    'category.restaurant': '餐飲',
    'category.shopping': '購物',
    'category.attraction': '景點',
    'category.culture': '文化',

    // Event Detail
    'eventDetail.editEvent': '編輯活動',
    'eventDetail.addEvent': '新增活動',
    'eventDetail.basicInfo': '基本資訊',
    'eventDetail.eventImages': '活動圖片',
    'eventDetail.coverImage': '封面圖片',
    'eventDetail.coverImageRequired': '(必填)',
    'eventDetail.coverImageTip': '建議尺寸：1200x800px，支援 JPG、PNG 格式',
    'eventDetail.activityAlbum': '活動相簿',
    'eventDetail.activityAlbumOptional': '(選填)',
    'eventDetail.maxImages': '最多上傳 6 張圖片，建議尺寸：800x600px',
    'eventDetail.uploadImage': '上傳圖片',
    'eventDetail.previewImage': '預覽圖片',
    'eventDetail.removeImage': '移除圖片',
    'eventDetail.maxImagesReached': '已達到最大上傳數量 (6張)',
    'eventDetail.dragUploadCover': '點擊或拖拽上傳封面圖片',
    'eventDetail.supportFormats': '支援 JPG、PNG 格式',
    'eventDetail.eventDetails': '活動詳情',
    'eventDetail.eventName': '活動名稱',
    'eventDetail.eventNamePlaceholder': '請輸入活動名稱',
    'eventDetail.eventCategory': '分類',
    'eventDetail.categoryPlaceholder': '請選擇分類',
    'eventDetail.organizer': '主辦單位',
    'eventDetail.organizerPlaceholder': '請輸入主辦單位',
    'eventDetail.eventDescription': '活動描述',
    'eventDetail.descriptionPlaceholder': '請輸入活動描述，或點擊右上角AI助手幫您美化文案...',
    'eventDetail.eventLocation': '活動地點',
    'eventDetail.locationPlaceholder': '請輸入活動地點',
    'eventDetail.detailedAddress': '詳細地址',
    'eventDetail.addressPlaceholder': '請輸入詳細地址',
    'eventDetail.eventDate': '活動日期',
    'eventDetail.startTime': '開始時間',
    'eventDetail.endTime': '結束時間',
    'eventDetail.settings': '設定',
    'eventDetail.status': '狀態',
    'eventDetail.maxAttendees': '最大參與人數',
    'eventDetail.participationFee': '參與費用',
    'eventDetail.yuan': '元',
    'eventDetail.registrationRequired': '需要報名',
    'eventDetail.noRegistrationRequired': '無需報名',
    'eventDetail.coverImageValidationError': '請上傳封面圖片',
    'eventDetail.createSuccess': '活動創建成功！',
    'eventDetail.updateSuccess': '活動更新成功！',
    'eventDetail.operationFailed': '操作失敗，請稍後再試',
    'eventDetail.coverImageUploadSuccess': '封面圖片上傳成功',
    'eventDetail.imageUploadSuccess': '圖片上傳成功',
    'eventDetail.imageRemoved': '圖片已移除',
    'eventDetail.coverImageRemoved': '封面圖片已移除',
    'eventDetail.createEvent': '創建活動',
    'eventDetail.updateEvent': '更新活動',
    'eventDetail.returnToEventList': '返回',
    'eventDetail.participatingBusinesses': '參與商家',
    'eventDetail.businessRemoved': '商家已移除',
    'eventDetail.aiWritingAssistant': 'AI寫作助手',
    'eventDetail.aiHelper': 'AI助手',
    'eventDetail.letAiOptimize': '讓AI幫您優化文案，提升活動吸引力',
    'eventDetail.oneClickOptimize': '一鍵美化文案',
    'eventDetail.optimizing': '正在美化中...',
    'eventDetail.generateTitle': '生成活動標題',
    'eventDetail.seoKeywords': 'SEO關鍵字建議',
    'eventDetail.featureInDevelopment': '功能開發中，敬請期待',
    'eventDetail.aiPoweredAssistant': '由GPT-4驅動的智能文案助手',
    'eventDetail.pleaseEnterDescription': '請先輸入活動描述內容',
    'eventDetail.aiOptimizeComplete': 'AI文案美化完成！已為您優化活動描述',
    'eventDetail.aiOptimizeFailed': 'AI美化失敗，請稍後再試',
    'eventDetail.ranking': '排名',
    'eventDetail.business': '商家',
    'eventDetail.performanceData': '表現數據',
    'eventDetail.clickRate': '點擊率',
    'eventDetail.viewDetails': '查看詳情',
    'eventDetail.removeBusiness': '移除商家',
    'eventDetail.mapView': '地圖視圖',
    'eventDetail.businessDistribution': '參與商家地理分佈',
    'eventDetail.distributionControl': '商家分布控制',
    'eventDetail.totalBusinesses': '總商家數',
    'eventDetail.displayingBusinesses': '顯示中商家',
    'eventDetail.businessCategory': '商家分類',
    'eventDetail.selectAll': '全部選擇',
    'eventDetail.deselectAll': '全部取消',
    'eventDetail.showTopPerformersOnly': '只顯示熱門商家',
    'eventDetail.viewRestaurants': '只看餐飲',
    'eventDetail.viewShopping': '只看購物',
    'eventDetail.manageBusiness': '管理商家',
    'eventDetail.businessManagement': '管理參與商家',
    'eventDetail.availableBusinesses': '可選商家',
    'eventDetail.participatingBusinessesCount': '參與商家',
    'eventDetail.businessSettingsUpdated': '商家設定已更新',
    'eventDetail.participatingBusinessesTab': '參與商家',
    'eventDetail.totalParticipating': '參與商家數',
    'eventDetail.totalPageViews': '總瀏覽量',
    'eventDetail.avgClickRate': '平均點擊率',
    'eventDetail.businessPerformanceRanking': '商家表現排行',
    'eventDetail.imagePreview': '圖片預覽',

    // Event categories
    'eventCategory.music': '音樂',
    'eventCategory.art': '藝術',
    'eventCategory.culture': '文化',
    'eventCategory.exhibition': '展覽',
    'eventCategory.festival': '節慶',
    'eventCategory.market': '市集',
    'eventCategory.workshop': '工作坊',
    'eventCategory.other': '其他',

    // Event status
    'eventStatus.draft': '草稿',
    'eventStatus.published': '已發布',
    'eventStatus.cancelled': '已取消',
    'eventStatus.completed': '已結束',
    
    // Common
    'common.welcome': '歡迎回來，王小明',
    'common.administrator': '管理員',
    'common.logout': '登出',
    'common.profile': '個人資料',
    'common.edit': '編輯',
    'common.delete': '刪除',
    'common.confirm': '確定',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.views': '瀏覽量',
    'common.clicks': '點擊量',
    'common.status': '狀態',
    'common.category': '分類',
    'common.name': '名稱',
    'common.description': '描述',
    'common.success': '成功',
    'common.processing': '處理中',
    'common.failed': '失敗',
    'common.actions': '操作',
    'common.loading': '載入中...',
    'common.search': '搜尋',
    'common.filter': '篩選',
    'common.all': '全部',
    'common.clear': '清除',
    'common.upload': '上傳',
    'common.download': '下載',
    'common.add': '新增',
    'common.close': '關閉',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.total': '總計',
    'common.selected': '已選擇',
    'common.items': '項',
    'common.page': '頁',
    'common.of': '共',
    'common.records': '筆記錄',
    'common.createdAt': '建立時間',
    'common.updatedAt': '最後更新',
    'common.deleteConfirm': '確定要刪除這個標籤嗎？',
    'common.deleteWarning': '刪除後將無法復原',
    'common.showing': '第',
    'common.uploadSuccess': '文件上傳成功',
    'common.uploadFailed': '文件上傳失敗',

    // Labels Management
    'labels.title': '特色標籤管理',
    'labels.description': '管理商家特色標籤，用於描述商家具體特色與服務內容',
    'labels.categoryNote': '商家主要分類（餐飲、購物、景點等）在商家編輯頁面設定',
    'labels.addNew': '新增標籤',
    'labels.edit': '編輯標籤',
    'labels.name': '標籤名稱',
    'labels.category': '分類',
    'labels.color': '顏色',
    'labels.totalCount': '總標籤數',
    'labels.totalUsage': '總使用次數',
    'labels.avgUsage': '平均使用次數',
    'labels.categoryCount': '分類數量',
    'labels.namePlaceholder': '請輸入標籤名稱',
    'labels.descriptionPlaceholder': '請輸入標籤描述',
    'labels.categoryPlaceholder': '請選擇標籤分類',
    'labels.colorPlaceholder': '請選擇標籤顏色',
    'labels.usageCount': '使用次數',
    'labels.createSuccess': '標籤創建成功！',
    'labels.updateSuccess': '標籤更新成功！',
    'labels.deleteSuccess': '標籤刪除成功！',
    'labels.operationFailed': '操作失敗，請稍後再試',
    'labels.confirmDelete': '確定要刪除此標籤嗎？',
    'labels.deleteWarning': '刪除後將無法復原，且已使用此標籤的商家將失去此標籤',
    'labels.categories.recommendation': '推薦',
    'labels.categories.status': '狀態',
    'labels.categories.feature': '特色',
    'labels.categories.facility': '設施',
    'labels.categories.promotion': '優惠',
    'labels.categories.other': '其他',
    'labels.colors.red': '紅色',
    'labels.colors.green': '綠色',
    'labels.colors.blue': '藍色',
    'labels.colors.purple': '紫色',
    'labels.colors.orange': '橙色',
    'labels.colors.cyan': '青色',
    'labels.colors.pink': '粉色',
    'labels.colors.yellow': '黃色',
    'labels.sampleData.hotRecommendation': '熱門推薦',
    'labels.sampleData.newOpening': '新開幕',
    'labels.sampleData.familyFriendly': '親子友善',
    'labels.sampleData.accessibleFacilities': '無障礙設施',
    'labels.sampleData.promotionalOffers': '優惠活動',
    'labels.sampleData.hotRecommended': '熱門推薦',
    'labels.sampleData.hotRecommendedDesc': '優質商家，高評價推薦',
    'labels.sampleData.newlyOpened': '新開幕',
    'labels.sampleData.newlyOpenedDesc': '最近新開幕的店家',
    'labels.sampleData.familyFriendlyDesc': '親子友善，適合全家前往',
    'labels.sampleData.accessible': '無障礙設施',
    'labels.sampleData.accessibleDesc': '完善的無障礙設施',
    'labels.sampleData.promotion': '優惠活動',
    'labels.sampleData.promotionDesc': '提供優惠活動與折扣',
    'labels.nameRequired': '請輸入標籤名稱',
    'labels.nameMaxLength': '標籤名稱不能超過20個字符',
    'labels.descriptionRequired': '請輸入標籤描述',
    'labels.descriptionMaxLength': '標籤描述不能超過100個字符',
    'labels.categoryRequired': '請選擇標籤分類',
    'labels.colorRequired': '請選擇標籤顏色',

    // Batch Upload
    'batchUpload.title': '批次上傳',
    'batchUpload.description': '一次上傳多筆商家資料，提高工作效率',
    'batchUpload.templateColumns': '模板欄位說明',
    'batchUpload.uploadFile': '上傳檔案',
    'batchUpload.quickActions': '快速操作',
    'batchUpload.uploadTip': '請先下載模板並按照格式填寫資料，支援 Excel (.xlsx) 或 CSV (.csv) 格式',
    'batchUpload.dragUpload': '點擊或拖拽檔案到此區域上傳',
    'batchUpload.supportedFormats': '支援 .xlsx, .csv 格式檔案',
    'batchUpload.downloadTemplate': '下載模板',
    'batchUpload.templateDescription': '模板使用說明',
    'batchUpload.templateInstructions': '使用說明：',
    'batchUpload.nameRequired': '商家名稱為必填欄位',
    'batchUpload.addressRequired': '地址為必填欄位',
    'batchUpload.maxRecords': '單次最多上傳 1000 筆記錄',
    'batchUpload.phoneFormat': '電話號碼格式：02-12345678 或 0912-345-678',
    'batchUpload.categoryOptions': '分類選項：餐飲、購物、景點、文化、其他',
    'batchUpload.uploadSuccess': '檔案上傳成功',
    'batchUpload.uploadFailed': '檔案上傳失敗',
    'batchUpload.processingRecords': '正在處理記錄...',
    'batchUpload.validationErrors': '資料驗證錯誤',
    'batchUpload.recordsProcessed': '已處理記錄數',
    'batchUpload.successCount': '成功',
    'batchUpload.failedCount': '失敗',
    'batchUpload.viewDetails': '查看詳情',
    'batchUpload.uploadHistory': '上傳歷史',
    'batchUpload.fileName': '檔案名稱',
    'batchUpload.uploadTime': '上傳時間',
    'batchUpload.status': '狀態',
    'batchUpload.recordCount': '記錄數',
    'batchUpload.errorMessage': '錯誤訊息',
    'batchUpload.downloadResult': '下載結果',
    'batchUpload.uploading': '上傳中...',
    'batchUpload.recentUploads': '最近上傳',
    'batchUpload.records': '筆記錄',
    'batchUpload.onlyExcelAllowed': '只能上傳 Excel 檔案！',
    'batchUpload.fileSizeLimit': '檔案大小不能超過 10MB！',
    'batchUpload.uploadSuccessMsg': '檔案上傳成功',
    'batchUpload.uploadFailedMsg': '檔案上傳失敗',
    'batchUpload.downloadingTemplate': '範本檔案下載中...',

    // Categories Management
    'categories.title': '分類管理',
    'categories.description': '管理商家分類，用於組織和分類不同類型的商家',
    'categories.addNew': '新增分類',
    'categories.editCategory': '編輯分類',
    'categories.addCategory': '新增分類',
    'categories.totalCategories': '總分類數',
    'categories.systemPredefined': '系統預設',
    'categories.customCategories': '自訂分類',
    'categories.totalBusinesses': '總商家數',
    'categories.color': '顏色',
    'categories.businessCount': '商家數量',
    'categories.type': '類型',
    'categories.actions': '操作',
    'categories.systemPredefinedType': '系統預設',
    'categories.customType': '自訂',
    'categories.categoryName': '分類名稱',
    'categories.icon': '圖示',
    'categories.nameRequired': '請輸入分類名稱',
    'categories.descriptionRequired': '請輸入分類描述',
    'categories.iconRequired': '請輸入圖示',
    'categories.colorRequired': '請選擇顏色',
    'categories.namePlaceholder': '請輸入分類名稱',
    'categories.descriptionPlaceholder': '請輸入分類描述',
    'categories.iconPlaceholder': '請輸入 emoji 圖示（如：🍽️）',
    'categories.colorPlaceholder': '請選擇分類顏色',
    'categories.cannotDeleteSystem': '無法刪除系統預設分類',
    'categories.cannotDeleteWithBusinesses': '無法刪除含有商家的分類',
    'categories.deleteConfirm': '確定要刪除此分類嗎？',
    'categories.deleteWarning': '刪除後將無法復原',
    'categories.deleteSuccess': '分類刪除成功！',
    'categories.updateSuccess': '分類更新成功！',
    'categories.createSuccess': '分類創建成功！',
    'categories.operationFailed': '操作失敗，請稍後再試',
    'categories.update': '更新',
    'categories.add': '新增',

    // Business Management
    'business.title': '商家管理',
    'business.batchUpload': '批次上傳',
    'business.addNew': '新增商家',
    'business.totalCount': '總商家數',
    'business.published': '已發布',
    'business.approved': '已審核',
    'business.pending': '審核待處理',
    'business.searchPlaceholder': '搜尋商家名稱、地址、分類...',
    'business.statusFilter': '狀態篩選',
    'business.categoryFilter': '分類篩選',
    'business.selectedItems': '已選擇',
    'business.items': '項',
    'business.batchPublish': '批量發布',
    'business.batchUnpublish': '批量下架',
    'business.businessPhoto': '商家照片',
    'business.businessInfo': '商家資訊',
    'business.views': '瀏覽量',
    'business.clickThroughRate': '點擊率',
    'business.onlineStatus': '上線狀態',
    'business.participatingEvents': '參與活動',
    'business.actions': '操作',
    'business.online': '已上線',
    'business.offline': '已下線',
    'business.editQuick': '快速編輯',
    'business.editPhoto': '編輯照片',
    'business.quickEdit': '快速編輯',
    'business.businessName': '商家名稱',
    'business.businessCategory': '商家分類',
    'business.businessAddress': '商家地址',
    'business.businessPhone': '聯絡電話',
    'business.businessDescription': '商家描述',
    'business.businessHours': '營業時間',
    'business.priceRange': '價格範圍',
    'business.paymentMethods': '付款方式',
    'business.amenities': '設施服務',
    'business.accessibility': '無障礙設施',
    'business.parking': '停車資訊',
    'business.businessStatus': '商家狀態',
    'business.statusUpdated': '狀態已更新',
    'business.updateSuccess': '商家資訊更新成功！',
    'business.operationFailed': '操作失敗，請稍後再試',
    'business.editPhotoTitle': '編輯商家照片',
    'business.currentPhoto': '當前照片',
    'business.uploadNewPhoto': '上傳新照片',
    'business.photoTip': '建議尺寸：400x300px，支援 JPG、PNG 格式，檔案大小 2MB 以下',
    'business.photoUploadSuccess': '照片上傳成功！',
    'business.photoUploadFailed': '照片上傳失敗',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.business': 'Business Management',
    'nav.batchUpload': 'Batch Upload',
    'nav.events': 'Event Management',
    'nav.analytics': 'Analytics',
    'nav.tags': 'Tag Management',
    'nav.categories': 'Category Management',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.totalBusinesses': 'Total Businesses',
    'dashboard.publishedBusinesses': 'Published Businesses',
    'dashboard.todayViews': 'Today\'s Views',
    'dashboard.runningEvents': 'Running Events',
    'dashboard.trafficTrend': 'Traffic Trend',
    'dashboard.topBusinesses': 'Top Businesses',
    'dashboard.recentActivity': 'Recent Updates',
    'dashboard.pendingTasks': 'Pending Tasks',
    'dashboard.pendingBusinesses': 'Pending Businesses',
    'dashboard.activeEvents': 'Draft Events',
    'dashboard.compareLastWeek': 'vs Last Week',
    'dashboard.viewDetails': 'View Details',
    'dashboard.viewAll': 'View All',
    'dashboard.editPhoto': 'Edit Photo',
    
    // Common
    'common.welcome': 'Welcome back, Wang Xiaoming',
    'common.administrator': 'Administrator',
    'common.logout': 'Logout',
    'common.profile': 'Profile',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.views': 'Views',
    'common.clicks': 'Clicks',
    'common.status': 'Status',
    'common.category': 'Category',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.success': 'Success',
    'common.processing': 'Processing',
    'common.failed': 'Failed',
    'common.actions': 'Actions',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.clear': 'Clear',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.total': 'Total',
    'common.selected': 'Selected',
    'common.items': 'items',
    'common.page': 'Page',
    'common.of': '/',
    'common.records': 'records',
    'common.createdAt': 'Created At',
    'common.updatedAt': 'Updated At',
    'common.deleteConfirm': 'Are you sure you want to delete this tag?',
    'common.deleteWarning': 'Once deleted, it cannot be recovered',
    'common.showing': 'Showing',
    'common.uploadSuccess': 'file uploaded successfully',
    'common.uploadFailed': 'file upload failed',

    // Labels Management
    'labels.title': 'Feature Tag Management',
    'labels.description': 'Manage feature tags for businesses to describe specific features and service content',
    'labels.categoryNote': 'Business main categories (dining, shopping, attractions, etc.) are set in the business edit page',
    'labels.addNew': 'Add Feature Tag',
    'labels.edit': 'Edit Tag',
    'labels.name': 'Tag Name',
    'labels.category': 'Category',
    'labels.color': 'Color',
    'labels.totalCount': 'Total Tags',
    'labels.totalUsage': 'Total Usage',
    'labels.avgUsage': 'Average Usage',
    'labels.categoryCount': 'Category Count',
    'labels.namePlaceholder': 'Enter tag name',
    'labels.descriptionPlaceholder': 'Enter tag description',
    'labels.categoryPlaceholder': 'Select tag category',
    'labels.colorPlaceholder': 'Select tag color',
    'labels.usageCount': 'Usage Count',
    'labels.createSuccess': 'Tag created successfully!',
    'labels.updateSuccess': 'Tag updated successfully!',
    'labels.deleteSuccess': 'Tag deleted successfully!',
    'labels.operationFailed': 'Operation failed, please try again',
    'labels.confirmDelete': 'Are you sure you want to delete this tag?',
    'labels.deleteWarning': 'Once deleted, it cannot be recovered and businesses using this tag will lose it',
    'labels.categories.recommendation': 'Recommendation',
    'labels.categories.status': 'Status',
    'labels.categories.feature': 'Feature',
    'labels.categories.facility': 'Facility',
    'labels.categories.promotion': 'Promotion',
    'labels.categories.other': 'Other',
    'labels.colors.red': 'Red',
    'labels.colors.green': 'Green',
    'labels.colors.blue': 'Blue',
    'labels.colors.purple': 'Purple',
    'labels.colors.orange': 'Orange',
    'labels.colors.cyan': 'Cyan',
    'labels.colors.pink': 'Pink',
    'labels.colors.yellow': 'Yellow',
    'labels.sampleData.hotRecommendation': 'Hot Recommendation',
    'labels.sampleData.newOpening': 'New Opening',
    'labels.sampleData.familyFriendly': 'Family Friendly',
    'labels.sampleData.accessibleFacilities': 'Accessible Facilities',
    'labels.sampleData.promotionalOffers': 'Promotional Offers',
    'labels.sampleData.hotRecommended': 'Hot Recommendation',
    'labels.sampleData.hotRecommendedDesc': 'Highly rated and recommended',
    'labels.sampleData.newlyOpened': 'New Opening',
    'labels.sampleData.newlyOpenedDesc': 'Recently opened businesses',
    'labels.sampleData.familyFriendlyDesc': 'Family-friendly environment',
    'labels.sampleData.accessible': 'Accessible Facilities',
    'labels.sampleData.accessibleDesc': 'Complete accessible facilities',
    'labels.sampleData.promotion': 'Promotional Offers',
    'labels.sampleData.promotionDesc': 'Various offers and discounts',
    'labels.nameRequired': 'Please enter tag name',
    'labels.nameMaxLength': 'Tag name cannot exceed 20 characters',
    'labels.descriptionRequired': 'Please enter tag description',
    'labels.descriptionMaxLength': 'Tag description cannot exceed 100 characters',
    'labels.categoryRequired': 'Please select tag category',
    'labels.colorRequired': 'Please select tag color',

    // Batch Upload
    'batchUpload.title': 'Batch Upload',
    'batchUpload.description': 'Upload multiple business records at once to improve work efficiency',
    'batchUpload.templateColumns': 'Template Column Description',
    'batchUpload.uploadFile': 'Upload File',
    'batchUpload.quickActions': 'Quick Actions',
    'batchUpload.uploadTip': 'Please download the template and fill in the data according to the format before uploading. Supports Excel (.xlsx) or CSV (.csv) format',
    'batchUpload.dragUpload': 'Click or drag the file to this area to upload',
    'batchUpload.supportedFormats': 'Supports .xlsx, .csv format files',
    'batchUpload.downloadTemplate': 'Download Template',
    'batchUpload.templateDescription': 'Template Usage Description',
    'batchUpload.templateInstructions': 'Usage Instructions:',
    'batchUpload.nameRequired': 'Business name is a required field',
    'batchUpload.addressRequired': 'Address is a required field',
    'batchUpload.maxRecords': 'Up to 1000 records can be uploaded at a time',
    'batchUpload.phoneFormat': 'Phone number format: 02-12345678 or 0912-345-678',
    'batchUpload.categoryOptions': 'Category Options: Dining, Shopping, Attractions, Culture, Other',
    'batchUpload.uploadSuccess': 'File uploaded successfully',
    'batchUpload.uploadFailed': 'File upload failed',
    'batchUpload.processingRecords': 'Processing records...',
    'batchUpload.validationErrors': 'Data validation error',
    'batchUpload.recordsProcessed': 'Records processed',
    'batchUpload.successCount': 'Success',
    'batchUpload.failedCount': 'Failed',
    'batchUpload.viewDetails': 'View Details',
    'batchUpload.uploadHistory': 'Upload History',
    'batchUpload.fileName': 'File Name',
    'batchUpload.uploadTime': 'Upload Time',
    'batchUpload.status': 'Status',
    'batchUpload.recordCount': 'Record Count',
    'batchUpload.errorMessage': 'Error Message',
    'batchUpload.downloadResult': 'Download Result',
    'batchUpload.uploading': 'Uploading...',
    'batchUpload.recentUploads': 'Recent Uploads',
    'batchUpload.records': 'records',
    'batchUpload.onlyExcelAllowed': 'Only Excel files are allowed!',
    'batchUpload.fileSizeLimit': 'File size cannot exceed 10MB!',
    'batchUpload.uploadSuccessMsg': 'File uploaded successfully',
    'batchUpload.uploadFailedMsg': 'File upload failed',
    'batchUpload.downloadingTemplate': 'Downloading template...',

    // Categories Management
    'categories.title': 'Category Management',
    'categories.description': 'Manage business categories to organize and categorize different types of businesses',
    'categories.addNew': 'Add Category',
    'categories.editCategory': 'Edit Category',
    'categories.addCategory': 'Add Category',
    'categories.totalCategories': 'Total Categories',
    'categories.systemPredefined': 'System Predefined',
    'categories.customCategories': 'Custom Categories',
    'categories.totalBusinesses': 'Total Businesses',
    'categories.color': 'Color',
    'categories.businessCount': 'Business Count',
    'categories.type': 'Type',
    'categories.actions': 'Actions',
    'categories.systemPredefinedType': 'System Predefined',
    'categories.customType': 'Custom',
    'categories.categoryName': 'Category Name',
    'categories.icon': 'Icon',
    'categories.nameRequired': 'Enter category name',
    'categories.descriptionRequired': 'Enter category description',
    'categories.iconRequired': 'Enter icon',
    'categories.colorRequired': 'Select color',
    'categories.namePlaceholder': 'Enter category name',
    'categories.descriptionPlaceholder': 'Enter category description',
    'categories.iconPlaceholder': 'Enter emoji icon (e.g.: 🍽️)',
    'categories.colorPlaceholder': 'Select category color',
    'categories.cannotDeleteSystem': 'Cannot delete system predefined category',
    'categories.cannotDeleteWithBusinesses': 'Cannot delete category with businesses',
    'categories.deleteConfirm': 'Are you sure you want to delete this category?',
    'categories.deleteWarning': 'Once deleted, it cannot be recovered',
    'categories.deleteSuccess': 'Category deleted successfully!',
    'categories.updateSuccess': 'Category updated successfully!',
    'categories.createSuccess': 'Category created successfully!',
    'categories.operationFailed': 'Operation failed, please try again',
    'categories.update': 'Update',
    'categories.add': 'Add',

    // Business Management
    'business.title': 'Business Management',
    'business.batchUpload': 'Batch Upload',
    'business.addNew': 'Add Business',
    'business.totalCount': 'Total Count',
    'business.published': 'Published',
    'business.approved': 'Approved',
    'business.pending': 'Pending',
    'business.searchPlaceholder': 'Search business name, address or category...',
    'business.statusFilter': 'Status Filter',
    'business.categoryFilter': 'Category Filter',
    'business.selectedItems': 'Selected',
    'business.items': 'items',
    'business.batchPublish': 'Batch Publish',
    'business.batchUnpublish': 'Batch Unpublish',
    'business.businessPhoto': 'Business Photo',
    'business.businessInfo': 'Business Info',
    'business.views': 'Views',
    'business.clickThroughRate': 'Click Rate',
    'business.onlineStatus': 'Online Status',
    'business.participatingEvents': 'Events',
    'business.actions': 'Actions',
    'business.online': 'Online',
    'business.offline': 'Offline',
    'business.editQuick': 'Quick Edit',
    'business.editPhoto': 'Edit Photo',
    'business.quickEdit': 'Quick Edit',
    'business.businessName': 'Business Name',
    'business.businessCategory': 'Category',
    'business.businessAddress': 'Address',
    'business.businessPhone': 'Phone',
    'business.businessDescription': 'Description',
    'business.businessHours': 'Hours',
    'business.priceRange': 'Price Range',
    'business.paymentMethods': 'Payment Methods',
    'business.amenities': 'Amenities',
    'business.accessibility': 'Accessibility',
    'business.parking': 'Parking',
    'business.businessStatus': 'Status',
    'business.statusUpdated': 'Status updated',
    'business.updateSuccess': 'Business updated successfully!',
    'business.operationFailed': 'Operation failed, please try again',
    'business.editPhotoTitle': 'Edit Business Photo',
    'business.currentPhoto': 'Current Photo',
    'business.uploadNewPhoto': 'Upload New Photo',
    'business.photoTip': 'Recommended size: 400x300px, supports JPG, PNG format, file size under 2MB',
    'business.photoUploadSuccess': 'Photo uploaded successfully!',
    'business.photoUploadFailed': 'Photo upload failed',
  },
  ja: {
    // Navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.business': '店舗管理',
    'nav.batchUpload': 'バッチアップロード',
    'nav.events': 'イベント管理',
    'nav.analytics': 'データ分析',
    'nav.tags': 'タグ管理',
    'nav.categories': 'カテゴリ管理',
    
    // Dashboard
    'dashboard.title': 'ダッシュボード',
    'dashboard.totalBusinesses': '総店舗数',
    'dashboard.publishedBusinesses': '公開済み店舗',
    'dashboard.todayViews': '今日の閲覧数',
    'dashboard.runningEvents': '実行中イベント',
    'dashboard.trafficTrend': 'トラフィック傾向',
    'dashboard.topBusinesses': '人気店舗ランキング',
    'dashboard.recentActivity': '最近の動向',
    'dashboard.pendingTasks': '保留中のタスク',
    'dashboard.pendingBusinesses': '審査待ち店舗',
    'dashboard.activeEvents': '編集中イベント',
    'dashboard.compareLastWeek': '先週比',
    'dashboard.viewDetails': '詳細を見る',
    'dashboard.viewAll': 'すべて見る',
    'dashboard.editPhoto': '写真を編集',
    
    // Common
    'common.welcome': 'お帰りなさい、王小明',
    'common.administrator': '管理者',
    'common.logout': 'ログアウト',
    'common.profile': 'プロフィール',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.confirm': '確認',
    'common.cancel': 'キャンセル',
    'common.save': '保存',
    'common.views': '閲覧数',
    'common.clicks': 'クリック数',
    'common.status': 'ステータス',
    'common.category': 'カテゴリ',
    'common.name': '名前',
    'common.description': '説明',
    'common.success': '成功',
    'common.processing': '処理中',
    'common.failed': '失敗',
    'common.actions': '操作',
    'common.loading': '読み込み中...',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.all': 'すべて',
    'common.clear': 'クリア',
    'common.upload': 'アップロード',
    'common.download': 'ダウンロード',
    'common.add': '追加',
    'common.close': '閉じる',
    'common.back': '戻る',
    'common.next': '次へ',
    'common.previous': '前へ',
    'common.total': '合計',
    'common.selected': '選択済み',
    'common.items': '項目',
    'common.page': 'ページ',
    'common.of': '/',
    'common.records': 'レコード',
    'common.createdAt': '作成時間',
    'common.updatedAt': '最終更新',
    'common.deleteConfirm': 'このタグを削除してもよろしいですか？',
    'common.deleteWarning': '削除後に元に戻すことはできません',
    'common.showing': '表示中',
    'common.uploadSuccess': 'ファイルアップロード成功',
    'common.uploadFailed': 'ファイルアップロード失敗',

    // Labels Management
    'labels.title': '特徴タグ管理',
    'labels.description': '店舗の特徴タグを管理し、具体的な特徴やサービス内容を説明します',
    'labels.categoryNote': '店舗の主要カテゴリ（飲食、ショッピング、アトラクションなど）は店舗編集ページで設定されます',
    'labels.addNew': '特徴タグを追加',
    'labels.edit': 'タグを編集',
    'labels.name': 'タグ名',
    'labels.category': 'カテゴリ',
    'labels.color': '色',
    'labels.totalCount': '総タグ数',
    'labels.totalUsage': '総使用回数',
    'labels.avgUsage': '平均使用回数',
    'labels.categoryCount': 'カテゴリ数',
    'labels.namePlaceholder': 'タグ名を入力',
    'labels.descriptionPlaceholder': 'タグの説明を入力',
    'labels.categoryPlaceholder': 'タグカテゴリを選択',
    'labels.colorPlaceholder': 'タグの色を選択',
    'labels.usageCount': '使用回数',
    'labels.createSuccess': 'タグが正常に作成されました！',
    'labels.updateSuccess': 'タグが正常に更新されました！',
    'labels.deleteSuccess': 'タグが正常に削除されました！',
    'labels.operationFailed': '操作に失敗しました。もう一度お試しください',
    'labels.confirmDelete': 'このタグを削除してもよろしいですか？',
    'labels.deleteWarning': '削除後は復元できず、このタグを使用している店舗は失われます',
    'labels.categories.recommendation': 'おすすめ',
    'labels.categories.status': 'ステータス',
    'labels.categories.feature': '特徴',
    'labels.categories.facility': '設備',
    'labels.categories.promotion': 'プロモーション',
    'labels.categories.other': 'その他',
    'labels.colors.red': '赤',
    'labels.colors.green': '緑',
    'labels.colors.blue': '青',
    'labels.colors.purple': '紫',
    'labels.colors.orange': 'オレンジ',
    'labels.colors.cyan': 'シアン',
    'labels.colors.pink': 'ピンク',
    'labels.colors.yellow': '黄',
    'labels.sampleData.hotRecommendation': '人気おすすめ',
    'labels.sampleData.newOpening': '新規オープン',
    'labels.sampleData.familyFriendly': 'ファミリー向け',
    'labels.sampleData.accessibleFacilities': 'バリアフリー設備',
    'labels.sampleData.promotionalOffers': 'プロモーション特典',
    'labels.sampleData.hotRecommended': '人気おすすめ',
    'labels.sampleData.hotRecommendedDesc': '優質商家，高評價推薦',
    'labels.sampleData.newlyOpened': '新開幕',
    'labels.sampleData.newlyOpenedDesc': '最近新開幕的店家',
    'labels.sampleData.familyFriendlyDesc': '親子友善，適合全家前往',
    'labels.sampleData.accessible': '無障礙設施',
    'labels.sampleData.accessibleDesc': '完善的無障礙設施',
    'labels.sampleData.promotion': '優惠活動',
    'labels.sampleData.promotionDesc': '提供優惠活動與折扣',
    'labels.nameRequired': 'タグ名を入力してください',
    'labels.nameMaxLength': 'タグ名は20文字以内で入力してください',
    'labels.descriptionRequired': 'タグの説明を入力してください',
    'labels.descriptionMaxLength': 'タグの説明は100文字以内で入力してください',
    'labels.categoryRequired': 'タグカテゴリを選択してください',
    'labels.colorRequired': 'タグの色を選択してください',

    // Batch Upload
    'batchUpload.title': 'バッチアップロード',
    'batchUpload.description': '一度に複数の業務レコードをアップロードして作業効率を向上させる',
    'batchUpload.templateColumns': 'テンプレートカラム説明',
    'batchUpload.uploadFile': 'ファイルアップロード',
    'batchUpload.quickActions': 'クイックアクション',
    'batchUpload.uploadTip': 'テンプレートをダウンロードしてデータを形式に従って入力してからアップロードしてください。Excel (.xlsx) または CSV (.csv) 形式をサポートします',
    'batchUpload.dragUpload': 'ファイルをこの領域にドラッグ＆ドロップしてアップロード',
    'batchUpload.supportedFormats': 'Excel (.xlsx), CSV (.csv) 形式のファイルをサポートします',
    'batchUpload.downloadTemplate': 'テンプレートダウンロード',
    'batchUpload.templateDescription': 'テンプレート利用説明',
    'batchUpload.templateInstructions': '利用方法：',
    'batchUpload.nameRequired': '店舗名は必須項目です',
    'batchUpload.addressRequired': '住所は必須項目です',
    'batchUpload.maxRecords': '一度に最大1000レコードのアップロード',
    'batchUpload.phoneFormat': '電話番号形式：02-12345678 または 0912-345-678',
    'batchUpload.categoryOptions': 'カテゴリオプション：ダイニング、ショッピング、アトラクション、カルチャー、その他',
    'batchUpload.uploadSuccess': 'ファイルアップロード成功',
    'batchUpload.uploadFailed': 'ファイルアップロード失敗',
    'batchUpload.processingRecords': 'レコード処理中...',
    'batchUpload.validationErrors': 'データ検証エラー',
    'batchUpload.recordsProcessed': '処理済みレコード数',
    'batchUpload.successCount': '成功',
    'batchUpload.failedCount': '失敗',
    'batchUpload.viewDetails': '詳細を見る',
    'batchUpload.uploadHistory': 'アップロード履歴',
    'batchUpload.fileName': 'ファイル名',
    'batchUpload.uploadTime': 'アップロード時間',
    'batchUpload.status': 'ステータス',
    'batchUpload.recordCount': 'レコード数',
    'batchUpload.errorMessage': 'エラーメッセージ',
    'batchUpload.downloadResult': 'ダウンロード結果',
    'batchUpload.uploading': 'アップロード中...',
    'batchUpload.recentUploads': '最近のアップロード',
    'batchUpload.records': 'レコード',
    'batchUpload.onlyExcelAllowed': 'Excelファイルのみアップロード可能です！',
    'batchUpload.fileSizeLimit': 'ファイルサイズは10MBを超えることはできません！',
    'batchUpload.uploadSuccessMsg': 'ファイルアップロード成功',
    'batchUpload.uploadFailedMsg': 'ファイルアップロード失敗',
    'batchUpload.downloadingTemplate': 'テンプレートファイルダウンロード中...',

    // Categories Management
    'categories.title': 'カテゴリ管理',
    'categories.description': 'ビジネスのカテゴリを管理し、異なるタイプのビジネスを整理および分類するために使用します',
    'categories.addNew': '新しいカテゴリを追加',
    'categories.editCategory': 'カテゴリを編集',
    'categories.addCategory': '新しいカテゴリを追加',
    'categories.totalCategories': '総カテゴリ数',
    'categories.systemPredefined': 'システムで事前定義された',
    'categories.customCategories': 'カスタムカテゴリ',
    'categories.totalBusinesses': '総ビジネス数',
    'categories.color': '色',
    'categories.businessCount': 'ビジネス数',
    'categories.type': 'タイプ',
    'categories.actions': 'アクション',
    'categories.systemPredefinedType': 'システムで事前定義された',
    'categories.customType': 'カスタム',
    'categories.categoryName': 'カテゴリ名',
    'categories.icon': 'アイコン',
    'categories.nameRequired': 'カテゴリ名を入力',
    'categories.descriptionRequired': 'カテゴリの説明を入力',
    'categories.iconRequired': 'アイコンを入力',
    'categories.colorRequired': '色を選択',
    'categories.namePlaceholder': 'カテゴリ名を入力',
    'categories.descriptionPlaceholder': 'カテゴリの説明を入力',
    'categories.iconPlaceholder': '絵文字アイコンを入力（例：🍽️）',
    'categories.colorPlaceholder': 'カテゴリの色を選択',
    'categories.cannotDeleteSystem': 'システムで事前定義されたカテゴリを削除できません',
    'categories.cannotDeleteWithBusinesses': 'ビジネスを含むカテゴリを削除できません',
    'categories.deleteConfirm': 'このカテゴリを削除してもよろしいですか？',
    'categories.deleteWarning': '削除後に元に戻すことはできません',
    'categories.deleteSuccess': 'カテゴリ削除成功！',
    'categories.updateSuccess': 'カテゴリ更新成功！',
    'categories.createSuccess': 'カテゴリ作成成功！',
    'categories.operationFailed': '操作に失敗しました。もう一度お試しください',
    'categories.update': '更新',
    'categories.add': '追加',

    // Business Management
    'business.title': '店舗管理',
    'business.batchUpload': 'バッチアップロード',
    'business.addNew': '店舗を追加',
    'business.totalCount': '総店舗数',
    'business.published': '公開中',
    'business.approved': '承認済み',
    'business.pending': '審査待ち',
    'business.searchPlaceholder': '店舗名、住所、カテゴリで検索...',
    'business.statusFilter': 'ステータスフィルター',
    'business.categoryFilter': 'カテゴリフィルター',
    'business.selectedItems': '選択済み',
    'business.items': '項目',
    'business.batchPublish': '一括公開',
    'business.batchUnpublish': '一括非公開',
    'business.businessPhoto': '店舗写真',
    'business.businessInfo': '店舗情報',
    'business.views': '閲覧数',
    'business.clickThroughRate': 'クリック率',
    'business.onlineStatus': '公開状態',
    'business.participatingEvents': 'イベント',
    'business.actions': '操作',
    'business.online': '公開中',
    'business.offline': '非公開',
    'business.editQuick': '簡易編集',
    'business.editPhoto': '写真編集',
    'business.quickEdit': '簡易編集',
    'business.businessName': '店舗名',
    'business.businessCategory': 'カテゴリ',
    'business.businessAddress': '住所',
    'business.businessPhone': '電話番号',
    'business.businessDescription': '店舗説明',
    'business.businessHours': '営業時間',
    'business.priceRange': '価格帯',
    'business.paymentMethods': '支払い方法',
    'business.amenities': '設備・サービス',
    'business.accessibility': 'バリアフリー設備',
    'business.parking': '駐車場情報',
    'business.businessStatus': '店舗ステータス',
    'business.statusUpdated': 'ステータスが更新されました',
    'business.updateSuccess': '店舗情報が正常に更新されました！',
    'business.operationFailed': '操作に失敗しました。もう一度お試しください',
    'business.editPhotoTitle': '店舗写真を編集',
    'business.currentPhoto': '現在の写真',
    'business.uploadNewPhoto': '新しい写真をアップロード',
    'business.photoTip': '推奨サイズ：400x300px、JPG、PNG形式をサポート、ファイルサイズ2MB以下',
    'business.photoUploadSuccess': '写真のアップロードが成功しました！',
    'business.photoUploadFailed': '写真のアップロードに失敗しました',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 